// Generated by CoffeeScript 1.6.3
$(document).ready(function() {
  var back, checkLocalStorage, clearStorage, init, loadNotes, setListeners;
  checkLocalStorage = function() {
    var e;
    try {
      return 'localStorage' in window;
    } catch (_error) {
      e = _error;
      return false;
    }
  };
  clearStorage = function() {
    return localStorage.clear();
  };
  back = function() {
    $('#back').hide();
    $('#newNote').hide();
    return $('#createNote').show();
  };
  setListeners = function() {
    $('#removeAll').on('click', function() {
      clearStorage();
      return alert('Removed all notes.');
    });
    $('#createNote').on('click', function() {
      $(this).hide();
      $('#back').show();
      return $('#newNote').show();
    });
    $('#saveNote').on('click', function() {
      var newNote, notes;
      notes = localStorage;
      console.log(localStorage);
      if (notes === !null && notes === !'') {

      } else {
        localStorage['chromeNotes'] = '';
        newNote = {
          id: '000',
          title: $('#title').val().trim(),
          content: $('#content').val().trim()
        };
        localStorage['chromeNotes'] = JSON.stringify(newNote);
        return back();
      }
    });
    return $('#back').on('click', function() {
      return back();
    });
  };
  loadNotes = function() {
    var notes;
    return notes = window['localStorage'].getItem('chromeNotes');
  };
  init = function() {
    var storageSupport;
    storageSupport = checkLocalStorage();
    $('#newNote').hide();
    $('#back').hide();
    if (storageSupport) {
      setListeners();
      return loadNotes();
    }
  };
  return init();
});
