// Generated by CoffeeScript 1.6.3
$(document).ready(function() {
  var back, calculateNewId, checkLocalStorage, clearStorage, init, loadNotes, setListeners;
  checkLocalStorage = function() {
    var e;
    try {
      return 'localStorage' in window;
    } catch (_error) {
      e = _error;
      return false;
    }
  };
  clearStorage = function() {
    return localStorage.clear();
  };
  back = function() {
    $('#back').hide();
    $('#newNote').hide();
    $('#createNote').show();
    return loadNotes();
  };
  calculateNewId = function() {
    var maxId, note, notes;
    if (!$.isEmptyObject(localStorage)) {
      notes = JSON.parse(localStorage['chromeNotes']);
      maxId = 0;
      for (note in notes) {
        if (note.id > maxId) {
          maxId = note.id;
        }
      }
      return maxId + 1;
    }
  };
  setListeners = function() {
    $('#removeAll').on('click', function() {
      var ans;
      ans = confirm("Are you sure you want to remove all notes?");
      if (ans) {
        return clearStorage();
      }
    });
    $('#createNote').on('click', function() {
      $(this).hide();
      $('#storedNotes').empty();
      $('#back').show();
      return $('#newNote').show();
    });
    $('#title').on('hide', function() {
      return $(this).empty();
    });
    $('#content').on('hide', function() {
      return $(this).empty();
    });
    $('#saveNote').on('click', function() {
      var ar, newId, newNote, notes;
      if (!$.isEmptyObject(localStorage)) {
        notes = JSON.parse(localStorage['chromeNotes']);
      } else {
        notes = [];
      }
      if (notes.length > 0) {
        newId = calculateNewId();
        newNote = {
          "id": newId,
          "title": $('#title').val().trim(),
          "content": $('#content').val().trim()
        };
        notes.push(newNote);
        ar = notes;
      } else {
        localStorage['chromeNotes'] = '';
        newNote = {
          "id": 0,
          "title": $('#title').val().trim(),
          "content": $('#content').val().trim()
        };
        ar = [newNote];
      }
      localStorage['chromeNotes'] = JSON.stringify(ar);
      return back();
    });
    $('#back').on('click', function() {
      return back();
    });
    return $('[id^=edit]').on('click', 'data', function() {
      return console.log(data);
    });
  };
  loadNotes = function() {
    var html, idx, notes, _results;
    if (!$.isEmptyObject(localStorage)) {
      notes = JSON.parse(localStorage['chromeNotes']);
      _results = [];
      for (idx in notes) {
        html = '<div id="note' + notes[idx].id + '">';
        html += '<img id="edit' + notes[idx].id + '" src="img/edit.png" height="15px" width="15px"/>';
        html += '<img id="delete' + notes[idx].id + '" src="img/delete.png" height="15px" width="15px"/>';
        html += notes[idx].title;
        html += '</div>';
        _results.push($('#storedNotes').append(html));
      }
      return _results;
    }
  };
  init = function() {
    var storageSupport;
    storageSupport = checkLocalStorage();
    $('#newNote').hide();
    $('#back').hide();
    if (storageSupport) {
      setListeners();
      return loadNotes();
    }
  };
  return init();
});
